"""Core agent package for cost-sensitive proof search."""

import logging

from .search.action import ActionCandidate, ActionGenerationRequest, ActionGenerator, StaticActionGenerator
from .search.budget import BudgetConfig, BudgetExhausted, BudgetManager, BudgetSnapshot
from .search.controller import AttemptRecord, ControllerConfig, ControllerResult, ProofController
from .search.execution import ExecutionMode
from .search.factory import StructuredModeUnavailableError, build_controller
from .search.metrics import (
    AttemptMetric,
    RunMetrics,
    attempt_metric,
    goal_fingerprint,
    goal_fingerprints,
    new_sample_id,
    run_metrics_payload,
    summarize_run,
)
from .search.proposer import CandidateLibraryGenerator, ProofSnippet
from .search.state_encoder import EncodedProofState, encode_proof_state
from .runtime.env_loader import load_dotenv
from .proof_system.lean import LeanAdapter
from .retrieval import LexicalLeanRetriever, RetrievalResult
from .agents import (
    AgentRole,
    ChatActionGenerator,
    ChatConfig,
    ChatContextSummarizer,
    ChatDriver,
    ChatFormalizationAgent,
    ChatTransport,
    ContextSummarizer,
    FormalizationAgent,
    FormalizationRequest,
    FormalizationResult,
    FunctionTool,
    LeanEnvironmentToolProvider,
    LeanProofToolProvider,
    ModelAdapterError,
    RoleModelConfig,
    ScaffoldChecker,
    StaticFormalizationAgent,
    Tool,
    ToolCall,
    ToolResult,
    UrllibChatTransport,
    VerifiedFormalizationCache,
    extract_missing_imports,
    extract_tool_calls,
    first_choice_message,
)
from .input import (
    InputNormalizer,
    LeanAdapterScaffoldChecker,
    NormalizedInput,
    ScaffoldValidationError,
    ValidationConfig,
    validate_scaffold_json,
)
from .proof_system.base import (
    BudgetSlice,
    CandidateEdit,
    CheckResult,
    DiagnosticCategory,
    ParsedFeedback,
    ProgressSignal,
    ProofSystemAdapter,
)
from .tasks.task_builder import LeanTaskBuilder, TaskBuildError, TaskBuilderConfig
from .tasks.types import ProofTask, TaskInputKind, TaskInputSpec
from .runtime.workspace import AttemptWorkspace, EphemeralCheckWorkspace, MaterializedCandidate
from .runtime.trace_store import JsonlTraceStore, result_events

logging.getLogger(__name__).addHandler(logging.NullHandler())

__all__ = [
    "ActionCandidate",
    "ActionGenerationRequest",
    "ActionGenerator",
    "AgentRole",
    "AttemptRecord",
    "AttemptWorkspace",
    "AttemptMetric",
    "BudgetConfig",
    "BudgetExhausted",
    "BudgetManager",
    "BudgetSlice",
    "BudgetSnapshot",
    "CandidateEdit",
    "CandidateLibraryGenerator",
    "ChatActionGenerator",
    "ChatConfig",
    "ChatContextSummarizer",
    "ChatDriver",
    "ChatFormalizationAgent",
    "CheckResult",
    "ContextSummarizer",
    "ControllerConfig",
    "ControllerResult",
    "DiagnosticCategory",
    "EncodedProofState",
    "EphemeralCheckWorkspace",
    "ExecutionMode",
    "FormalizationAgent",
    "FormalizationRequest",
    "FormalizationResult",
    "FunctionTool",
    "InputNormalizer",
    "LeanAdapter",
    "LeanAdapterScaffoldChecker",
    "LeanEnvironmentToolProvider",
    "LeanProofToolProvider",
    "LeanTaskBuilder",
    "LexicalLeanRetriever",
    "load_dotenv",
    "JsonlTraceStore",
    "MaterializedCandidate",
    "ModelAdapterError",
    "NormalizedInput",
    "RunMetrics",
    "ScaffoldChecker",
    "ScaffoldValidationError",
    "SummarizationRequest",
    "SummarizationResult",
    "Tool",
    "ToolCall",
    "ToolResult",
    "ValidationConfig",
    "validate_scaffold_json",
    "ParsedFeedback",
    "ProofSnippet",
    "ProgressSignal",
    "ProofController",
    "ProofSystemAdapter",
    "ProofTask",
    "RetrievalResult",
    "RoleModelConfig",
    "StructuredModeUnavailableError",
    "attempt_metric",
    "build_controller",
    "goal_fingerprint",
    "goal_fingerprints",
    "new_sample_id",
    "result_events",
    "run_metrics_payload",
    "StaticActionGenerator",
    "StaticFormalizationAgent",
    "summarize_run",
    "TaskBuildError",
    "TaskBuilderConfig",
    "TaskInputKind",
    "TaskInputSpec",
    "UrllibChatTransport",
    "VerifiedFormalizationCache",
    "encode_proof_state",
    "extract_missing_imports",
    "extract_tool_calls",
    "first_choice_message",
]
