"""Typed structured action proposal package."""
from __future__ import annotations

from .core import (
    FAILURE_HYPOTHESES_KEY,
    LEGACY_ACTION_KEY,
    LEGACY_KIND_DEFERRED,
    SUPPORTED_PROPOSAL_KINDS,
    StructuredActionGenerator,
    StructuredActionProposal,
    _LegacyActionGeneratorAdapter,
    adapt_legacy_generator,
    structured_action_proposal_from_dict,
)
from .types import (
    PAYLOAD_KIND_CAPABILITY_TEST,
    PAYLOAD_KIND_CHANGE_REPRESENTATION,
    PAYLOAD_KIND_DECOMPOSE,
    PAYLOAD_KIND_IMPLEMENT,
    PAYLOAD_KIND_PROPOSE_ARGUMENT,
    PAYLOAD_KIND_REFINE_ARGUMENT,
    ActionPayload,
    AlignmentSpec,
    ArgumentStepSpec,
    CapabilityTestPayload,
    ChangeRepresentationPayload,
    DecomposeChildSpec,
    DecomposePayload,
    ImplementPayload,
    ProposeArgumentPayload,
    RefineArgumentPayload,
    alignment_spec_from_dict,
    argument_step_spec_from_dict,
    capability_test_payload_from_dict,
    change_representation_payload_from_dict,
    decompose_child_spec_from_dict,
    decompose_payload_from_dict,
    propose_argument_payload_from_dict,
    refine_argument_payload_from_dict,
)

__all__ = [
    "FAILURE_HYPOTHESES_KEY",
    "LEGACY_ACTION_KEY",
    "LEGACY_KIND_DEFERRED",
    "SUPPORTED_PROPOSAL_KINDS",
    "StructuredActionGenerator",
    "StructuredActionProposal",
    "_LegacyActionGeneratorAdapter",
    "adapt_legacy_generator",
    "structured_action_proposal_from_dict",
    "PAYLOAD_KIND_CAPABILITY_TEST",
    "PAYLOAD_KIND_CHANGE_REPRESENTATION",
    "PAYLOAD_KIND_DECOMPOSE",
    "PAYLOAD_KIND_IMPLEMENT",
    "PAYLOAD_KIND_PROPOSE_ARGUMENT",
    "PAYLOAD_KIND_REFINE_ARGUMENT",
    "ActionPayload",
    "AlignmentSpec",
    "ArgumentStepSpec",
    "CapabilityTestPayload",
    "ChangeRepresentationPayload",
    "DecomposeChildSpec",
    "DecomposePayload",
    "ImplementPayload",
    "ProposeArgumentPayload",
    "RefineArgumentPayload",
    "alignment_spec_from_dict",
    "argument_step_spec_from_dict",
    "capability_test_payload_from_dict",
    "change_representation_payload_from_dict",
    "decompose_child_spec_from_dict",
    "decompose_payload_from_dict",
    "propose_argument_payload_from_dict",
    "refine_argument_payload_from_dict",
]
